import client from "@/client";
import About from "@/components/sections/About";
import Hero from "@/components/Hero";
import Layout from "@/components/Layout";
import Projects from "@/components/sections/Projects";
import Head from "next/head";

export default function Home({ projects }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Projects projects={projects} showViewAll={true} />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const projects = await client.fetch(`
      *[_type == "project"]
    `);
  return {
    props: {
      projects,
    },
  };
}
